name: dropdown_button2
description: Flutter's core Dropdown Button widget with steady dropdown menu and many options you can customize to your needs.
version: 2.3.4
repository: https://github.com/AhmedLSayed9/dropdown_button2
issue_tracker: https://github.com/AhmedLSayed9/dropdown_button2/issues

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  file: ^7.0.0
  platform: ^3.1.4

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    # Used for golden tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  assets:
    - assets/images/
